In [61]:
import os
import pandas as pd

In [62]:
os.getcwd()

'c:\\Users\\bfran\\Ironhack\\Week 3\\Project'

In [63]:
# Saves as df data pulled from UN Comtrade Database
df = pd.read_csv("BRZ Imports from PRY.csv", encoding='unicode_escape')

In [64]:
# Displays dataframe
df

,TypeCode,FreqCode,RefPeriodId,RefYear,RefMonth,Period,ReporterCode,ReporterISO,ReporterDesc,FlowCode,...,IsNetWgtEstimated,GrossWgt,IsGrossWgtEstimated,Cifvalue,Fobvalue,PrimaryValue,LegacyEstimationFlag,IsReported,IsAggregate,Unnamed: 47
0,C,A,20230101,2023,52,2023,76,BRA,Brazil,M,...,False,0,False,164152498,1.627485e+08,164152498,0,False,True,NaN
1,C,A,20230101,2023,52,2023,76,BRA,Brazil,M,...,False,0,False,121449077,1.205179e+08,121449077,0,False,True,NaN
2,C,A,20230101,2023,52,2023,76,BRA,Brazil,M,...,False,0,False,121449077,1.205179e+08,121449077,0,False,True,NaN
3,C,A,20230101,2023,52,2023,76,BRA,Brazil,M,...,False,0,False,36668432,3.635951e+07,36668432,0,False,True,NaN
4,C,A,20230101,2023,52,2023,76,BRA,Brazil,M,...,False,0,False,142257,1.406430e+05,142257,0,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,C,A,20230101,2023,52,2023,76,BRA,Brazil,M,...,False,0,False,1428127,1.408886e+06,1428127,0,False,True,NaN
856,C,A,20230101,2023,52,2023,76,BRA,Brazil,M,...,False,0,False,596432,5.889700e+05,596432,0,False,True,NaN
857,C,A,20230101,2023,52,2023,76,BRA,Brazil,M,...,False,0,False,52108,5.169500e+04,52108,0,False,True,NaN
858,C,A,20230101,2023,52,2023,76,BRA,Brazil,M,...,False,0,False,52108,5.169500e+04,52108,0,False,True,NaN
859,C,A,20230101,2023,52,2023,76,BRA,Brazil,M,...,False,0,False,3013649715,2.952386e+09,3013649715,0,False,True,NaN

In [65]:
# Defines useful columns to keep
columns_to_keep = ['RefYear','ReporterDesc','FlowDesc','PartnerDesc','CmdCode','CmdDesc','AggrLevel','QtyUnitAbbr','Qty','NetWgt','Cifvalue','Fobvalue']

In [66]:
# Saves the dataframe with only those columns that have useful data
df = df.loc[:,columns_to_keep]

In [67]:
# Saves the dataframe keeping only those rows with an HS level of 6 digits
df = df[df['AggrLevel'] == 6]

In [68]:
# Removes the now useless AggrLevel column
df = df.drop(columns= 'AggrLevel')

In [69]:
# Renames columns in order to provide clarity and to make merging datasets easier later
df.rename(columns = {'RefYear':'year',
          'ReporterDesc': 'reporter',
          'FlowDesc':'trade_flow',
          'PartnerDesc':'partner',
          'CmdCode':'hs_code',
          'CmdDesc':'commodity',
          'QtyUnitAbbr':'unit_type',
          'Qty':'quantity',
          'NetWgt':'net_weight',
          'Cifvalue':'cif_value',
          'Fobvalue':'fob_value'},
          inplace=True)

# Displays new dataframe with new column names
df

,year,reporter,trade_flow,partner,hs_code,commodity,unit_type,quantity,net_weight,cif_value,fob_value
2,2023,Brazil,Import,Paraguay,020130,"Meat; of bovine animals, boneless cuts, fresh ...",kg,20859060.0,20859060.0,121449077,120517874.0
4,2023,Brazil,Import,Paraguay,020220,"Meat; of bovine animals, cuts with bone in (ex...",kg,52443.0,52443.0,142257,140643.0
5,2023,Brazil,Import,Paraguay,020230,"Meat; of bovine animals, boneless cuts, frozen",kg,7144609.0,7144609.0,36526175,36218864.0
7,2023,Brazil,Import,Paraguay,020622,"Offal, edible; of bovine animals, livers, frozen",kg,2692900.0,2692900.0,3173894,3053319.0
8,2023,Brazil,Import,Paraguay,020629,"Offal, edible; of bovine animals, (other than ...",kg,978823.0,978823.0,2784282,2749729.0
...,...,...,...,...,...,...,...,...,...,...,...
852,2023,Brazil,Import,Paraguay,960390,"Brooms, brushes, mops, feather dusters, squeeg...",u,227239.0,222937.0,970791,954776.0
854,2023,Brazil,Import,Paraguay,960711,Slide fasteners; fitted with chain scoops of b...,kg,95679.0,95679.0,305714,302419.0
855,2023,Brazil,Import,Paraguay,960719,Slide fasteners; other than those fitted with ...,kg,553771.0,553771.0,1428127,1408886.0
856,2023,Brazil,Import,Paraguay,960720,Slide fasteners; parts,kg,222643.0,222643.0,596432,588970.0
858,2023,Brazil,Import,Paraguay,960990,"Pastels, drawing charcoals, writing or drawing...",kg,16508.0,16508.0,52108,51695.0

In [57]:
# Checks values of unit types to be updated
df['unit_type'].value_counts()

unit_type
kg          370
u           117
m³            7
m²            4
2u            3
l             2
1000 kWh      1
1000u         1
Name: count, dtype: int64

In [70]:
# Creates a dictionary with old unit_type values and the values we want to change them to. 
# Updated values provide clarity in regards to unit types
replace_dict = {
    '1000u':'thousands_of_units',
    '2u':'pairs_of_units',
    'l':'liters',
    'm²':'square_meters',
    'm³':'cubic_meters',
    'u':'units'
}

In [59]:
# Actually updates the unit types. 
df['unit_type'] = df['unit_type'].replace(replace_dict)

In [60]:
# Displays modified values in unit_types
df['unit_type'].value_counts()

unit_type
kg                    370
units                 117
cubic_meters            7
square_meters           4
pairs_of_units          3
liters                  2
1000 kWh                1
thousands_of_units      1
Name: count, dtype: int64

In [71]:
# Changes value in trade_flow column from Import to imported_from to provide clarity of trade flows.
df['trade_flow']=df['trade_flow'].replace('Import','imported_from')

In [72]:
# Saves cleaned dataframe as a new .csv file for future use. 
df.to_csv('cleaned BRZ Imports from PRY.csv',index=False)

In [73]:
# Saves data from new .csv file as newdf to ensure that everything worked. 
newdf = pd.read_csv('cleaned BRZ Imports from PRY.csv')

newdf

,year,reporter,trade_flow,partner,hs_code,commodity,unit_type,quantity,net_weight,cif_value,fob_value
0,2023,Brazil,imported_from,Paraguay,20130,"Meat; of bovine animals, boneless cuts, fresh ...",kg,20859060.0,20859060.0,121449077,120517874.0
1,2023,Brazil,imported_from,Paraguay,20220,"Meat; of bovine animals, cuts with bone in (ex...",kg,52443.0,52443.0,142257,140643.0
2,2023,Brazil,imported_from,Paraguay,20230,"Meat; of bovine animals, boneless cuts, frozen",kg,7144609.0,7144609.0,36526175,36218864.0
3,2023,Brazil,imported_from,Paraguay,20622,"Offal, edible; of bovine animals, livers, frozen",kg,2692900.0,2692900.0,3173894,3053319.0
4,2023,Brazil,imported_from,Paraguay,20629,"Offal, edible; of bovine animals, (other than ...",kg,978823.0,978823.0,2784282,2749729.0
...,...,...,...,...,...,...,...,...,...,...,...
501,2023,Brazil,imported_from,Paraguay,960390,"Brooms, brushes, mops, feather dusters, squeeg...",u,227239.0,222937.0,970791,954776.0
502,2023,Brazil,imported_from,Paraguay,960711,Slide fasteners; fitted with chain scoops of b...,kg,95679.0,95679.0,305714,302419.0
503,2023,Brazil,imported_from,Paraguay,960719,Slide fasteners; other than those fitted with ...,kg,553771.0,553771.0,1428127,1408886.0
504,2023,Brazil,imported_from,Paraguay,960720,Slide fasteners; parts,kg,222643.0,222643.0,596432,588970.0
505,2023,Brazil,imported_from,Paraguay,960990,"Pastels, drawing charcoals, writing or drawing...",kg,16508.0,16508.0,52108,51695.0