In [2]:
#importing packages we need
import pandas as pd
import os 
import numpy as np

In [3]:
#gets current working directory 
os.getcwd()

'c:\\Users\\wilfe\\OneDrive\\Documents\\GitHub\\Ironhack-PRY-BRZ-MGA'

In [5]:
#saves as df previously created mx_compare2 file 
df = pd.read_csv('mx_compare2.csv')

In [6]:
df

,hs_code,br_x_q,br_x_unit,py_m_q,py_m_unit,br_x_nt_wgt,py_m_nt_wgt,br_x_value,itic_rate,applied_tariff,adj_x_value,py_m_value,trade_gap,est_tax_loss,wgt_gap,value_ratio,wgt_ratio,density
0,10310,641.0,units,0.00,NR,58244.0,55587.0,649041.0,1.08,0.0,703300.83,649040.72,54260.11,0.00,2657.0,0.92,0.95,0.97
1,10392,904.0,units,2690.91,units,79649.0,79650.0,579106.0,1.08,2.0,627519.26,579105.90,48413.36,968.27,-1.0,0.92,1.0,0.92
2,10511,13417432.0,units,0.00,NR,642645.0,667138.8,10782248.0,1.06,1.0,11457216.72,10969520.83,487695.89,4876.96,-24493.8,0.96,1.04,0.92
3,20130,3428542.0,kg,3828180.00,kg,3428542.0,3828180.0,11463570.0,1.04,12.0,11876258.52,14030355.31,-2154096.79,-258491.61,-399638.0,1.18,1.12,1.06
4,20220,1822983.0,kg,1845790.00,kg,1822983.0,1845790.0,6153697.0,1.04,10.0,6401075.62,6235915.96,165159.66,16515.97,-22807.0,0.97,1.01,0.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3056,910211,2.0,units,0.00,NR,1.0,0.0,580.0,1.03,6.0,596.24,0.00,596.24,35.77,1.0,NMR,NMR,NaN
3057,910229,100.0,units,0.00,NR,3.0,0.0,60.0,1.03,20.0,61.68,0.00,61.68,12.34,3.0,NMR,NMR,NaN
3058,910521,10.0,units,0.00,NR,4.0,0.0,103.0,1.04,6.0,107.64,0.00,107.64,6.46,4.0,NMR,NMR,NaN
3059,950632,22.0,units,0.00,NR,14.0,0.0,1031.0,1.04,6.0,1074.10,0.00,1074.10,64.45,14.0,NMR,NMR,NaN
3060,961320,17.0,units,0.00,NR,2.0,0.0,360.0,1.04,18.0,372.96,0.00,372.96,67.13,2.0,NMR,NMR,NaN

Creating Subsets

In [7]:
# Creates two subsets

# This subset removes rows in which there were no reported import or export weights or values
df_full_rep = df[(df['value_ratio'] != "NXR") 
                 & (df['value_ratio'] != "NMR") 
                 & (df['wgt_ratio'] != "NXR") 
                 & (df['wgt_ratio'] != "NMR")]


# This subset includes only those rows with incomplete reporting.
df_missing_rep = df[~((df['value_ratio'] != "NXR") 
                      & (df['value_ratio'] != "NMR") 
                      & (df['wgt_ratio'] != "NXR") 
                      & (df['wgt_ratio'] != "NMR"))]

In [8]:
# Prints the shape of each dataset
print("Shape of full reporting data set: ",df_full_rep.shape)
print("Shape of missing reporting data set: ",df_missing_rep.shape)

Shape of full reporting data set:  (2734, 18)
Shape of missing reporting data set:  (327, 18)

In [9]:
# Counts the occurrences of unique values in value ratio column
df_missing_rep['value_ratio'].value_counts()

#in this data the problem of No Reporting is almost evenly split amongst countries

value_ratio
NMR     159
NXR     154
0.95      2
3.96      1
0.88      1
0.03      1
0.83      1
0.61      1
0.87      1
0.82      1
0.78      1
0.97      1
0.02      1
0.15      1
2.65      1
Name: count, dtype: int64

Comparing data that can be compared

In [12]:
# Convert both columns to numeric type, coercing any non-numeric values to NaN
df_full_rep['value_ratio'] = pd.to_numeric(df_full_rep['value_ratio'], errors='coerce')
df_full_rep['wgt_ratio'] = pd.to_numeric(df_full_rep['wgt_ratio'], errors='coerce')
df_full_rep['density'] = pd.to_numeric(df_full_rep['density'], errors='coerce')

# Filters out all rows where values are close to what we expect them to be. 
condition = ~((df_full_rep['value_ratio'] > 0.85) & (df_full_rep['value_ratio'] < 1.15) & 
              (df_full_rep['wgt_ratio'] > 0.85) & (df_full_rep['wgt_ratio'] < 1.15) &
              (df_full_rep['density'] > 0.85) & (df_full_rep['density'] < 1.15))

# Applies filter condition
df_full_rep = df_full_rep[condition]

C:\Users\wilfe\AppData\Local\Temp\ipykernel_12668\106245766.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_rep['value_ratio'] = pd.to_numeric(df_full_rep['value_ratio'], errors='coerce')
C:\Users\wilfe\AppData\Local\Temp\ipykernel_12668\106245766.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_rep['wgt_ratio'] = pd.to_numeric(df_full_rep['wgt_ratio'], errors='coerce')
C:\Users\wilfe\AppData\Local\Temp\ipykernel_12668\106245766.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_rep['density'] = pd.to_numeric(df_full_rep['density'], errors='coerce')

In [13]:
df_full_rep.shape

(1600, 18)

In [15]:
# Filters out all rows where values are close to what we expect them to be. 
condition_sm = ((df_full_rep['value_ratio'] < 0.85) & 
               (df_full_rep['wgt_ratio'] < 0.85) &
               ((df_full_rep['density'] < 1.15)))

In [16]:
#creating subset for possible smuggling 
sm = df_full_rep[condition_sm]

sm

,hs_code,br_x_q,br_x_unit,py_m_q,py_m_unit,br_x_nt_wgt,py_m_nt_wgt,br_x_value,itic_rate,applied_tariff,adj_x_value,py_m_value,trade_gap,est_tax_loss,wgt_gap,value_ratio,wgt_ratio,density
12,20714,31512.0,kg,3504.00,kg,31512.00,3504.00,73065.0,1.05,10.00,77010.51,7266.90,69743.61,6974.36,28008.00,0.09,0.11,0.85
98,100610,146960.0,kg,85320.00,kg,146960.00,85320.00,53741.0,1.11,6.67,59770.74,32594.88,27175.86,1811.72,61640.00,0.55,0.58,0.94
106,110290,5755.0,kg,4413.20,kg,5755.00,4413.20,5926.0,1.06,10.00,6304.08,4244.57,2059.51,205.95,1341.80,0.67,0.77,0.88
119,110814,5219721.0,kg,3282572.50,kg,5219721.00,3282572.50,4916818.0,1.13,10.00,5557971.07,3108413.94,2449557.13,244955.71,1937148.50,0.56,0.63,0.89
120,110820,3.0,kg,2.50,kg,3.00,2.50,43.0,1.13,10.00,48.61,2.00,46.61,4.66,0.50,0.04,0.83,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,940290,5841.0,kg,4279.93,kg,5841.00,4279.93,84105.0,1.07,5.33,90160.56,72651.78,17508.78,933.80,1561.07,0.81,0.73,1.10
2878,960330,511230.0,units,0.00,NR,7774.18,5964.89,156723.0,1.04,18.00,162647.13,136033.13,26614.00,4790.52,1809.30,0.84,0.77,1.09
2880,960350,20367.0,units,0.00,NR,12361.89,8966.46,137885.0,1.04,18.00,143097.05,96823.99,46273.06,8329.15,3395.43,0.68,0.73,0.93
2894,960840,66284.0,units,15414.50,units,1260.00,536.95,35376.0,1.03,18.00,36614.16,10101.71,26512.45,4772.24,723.05,0.28,0.43,0.65
2906,961380,20621.0,units,0.00,NR,1113.52,886.04,30430.0,1.04,18.00,31525.48,17988.95,13536.53,2436.58,227.48,0.57,0.80,0.72

Adding in HS Code classification

In [18]:
#importing tariff data to pull commodity descriptions 

tariffs = pd.read_csv("brz_app_tariffs.csv")

tariffs.columns

Index(['reporter', 'year', 'hs_code', 'applied_tariff', 'commodity'], dtype='object')

In [19]:
#taking out unnecessary columns 

columns = ['reporter','year','applied_tariff']

tariffs = tariffs.drop(columns=columns)

tariffs.shape

(16584, 2)

In [24]:
#creating a list of the HS Codes present on possible smuggling list 
sm_codes = sm['hs_code']

sm_com = pd.merge(sm_codes, tariffs, on='hs_code', how='left')

In [22]:
#dropped duplicate entries 
sm_com.drop_duplicates(inplace=True)

In [23]:
#the list of products possibly used as a cover for smuggling 
sm_com

     hs_code                                          commodity
0      20714  Frozen cuts and edible offal of fowls of the s...
3     100610                 Rice in the husk, "paddy" or rough
6     110290      Cereal flours (excl. wheat, meslin and maize)
9     110814                                      Manioc starch
12    110820                                             Inulin
..       ...                                                ...
651   940290  Operating tables, examination tables, and othe...
654   960330  Artists' brushes, writing brushes and similar ...
657   960350  Brushes constituting parts of machines, applia...
660   960840                      Propelling or sliding pencils
663   961380  Lighters (excl. gas fuelled pocket lighters, a...

[231 rows x 2 columns]