In [43]:
#importing packages we need
import pandas as pd
import os 
import numpy as np

In [44]:
#gets current working directory 
os.getcwd()

'c:\\Users\\wilfe\\OneDrive\\Documents\\GitHub\\Ironhack-PRY-BRZ-MGA'

In [45]:
#saves as df previously created mx_compare2 file 
df = pd.read_csv('mx_compare2.csv')

In [46]:
df

,hs_code,br_x_q,br_x_unit,py_m_q,py_m_unit,br_x_nt_wgt,py_m_nt_wgt,br_x_value,itic_rate,applied_tariff,adj_x_value,py_m_value,trade_gap,est_tax_loss,wgt_gap,value_ratio,wgt_ratio,density
0,10310,641.0,units,0.00,NR,58244.0,55587.0,649041.0,1.08,0.0,703300.83,649040.72,54260.11,0.00,2657.0,0.92,0.95,0.97
1,10392,904.0,units,2690.91,units,79649.0,79650.0,579106.0,1.08,2.0,627519.26,579105.90,48413.36,968.27,-1.0,0.92,1.0,0.92
2,10511,13417432.0,units,0.00,NR,642645.0,667138.8,10782248.0,1.06,1.0,11457216.72,10969520.83,487695.89,4876.96,-24493.8,0.96,1.04,0.92
3,20130,3428542.0,kg,3828180.00,kg,3428542.0,3828180.0,11463570.0,1.04,12.0,11876258.52,14030355.31,-2154096.79,-258491.61,-399638.0,1.18,1.12,1.06
4,20220,1822983.0,kg,1845790.00,kg,1822983.0,1845790.0,6153697.0,1.04,10.0,6401075.62,6235915.96,165159.66,16515.97,-22807.0,0.97,1.01,0.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3056,910211,2.0,units,0.00,NR,1.0,0.0,580.0,1.03,6.0,596.24,0.00,596.24,35.77,1.0,NMR,NMR,NaN
3057,910229,100.0,units,0.00,NR,3.0,0.0,60.0,1.03,20.0,61.68,0.00,61.68,12.34,3.0,NMR,NMR,NaN
3058,910521,10.0,units,0.00,NR,4.0,0.0,103.0,1.04,6.0,107.64,0.00,107.64,6.46,4.0,NMR,NMR,NaN
3059,950632,22.0,units,0.00,NR,14.0,0.0,1031.0,1.04,6.0,1074.10,0.00,1074.10,64.45,14.0,NMR,NMR,NaN
3060,961320,17.0,units,0.00,NR,2.0,0.0,360.0,1.04,18.0,372.96,0.00,372.96,67.13,2.0,NMR,NMR,NaN

In [58]:
hs_classification = pd.read_csv('brz_app_tariffs.csv')

In [59]:
hs_classification.drop(['reporter','year','applied_tariff'], axis=1, inplace=True)

In [60]:
df = df.merge(hs_classification, on='hs_code', how='inner')

In [61]:
df

,hs_code,br_x_q,br_x_unit,py_m_q,py_m_unit,br_x_nt_wgt,py_m_nt_wgt,br_x_value,itic_rate,applied_tariff,adj_x_value,py_m_value,trade_gap,est_tax_loss,wgt_gap,value_ratio,wgt_ratio,density,commodity
0,10310,641.0,units,0.00,NR,58244.0,55587.0,649041.0,1.08,0.0,703300.83,649040.72,54260.11,0.00,2657.0,0.92,0.95,0.97,Pure-bred breeding swine
1,10310,641.0,units,0.00,NR,58244.0,55587.0,649041.0,1.08,0.0,703300.83,649040.72,54260.11,0.00,2657.0,0.92,0.95,0.97,Pure-bred breeding swine
2,10310,641.0,units,0.00,NR,58244.0,55587.0,649041.0,1.08,0.0,703300.83,649040.72,54260.11,0.00,2657.0,0.92,0.95,0.97,Pure-bred breeding swine
3,10392,904.0,units,2690.91,units,79649.0,79650.0,579106.0,1.08,2.0,627519.26,579105.90,48413.36,968.27,-1.0,0.92,1.0,0.92,"Live pure-bred swine, weighing >= 50 kg (excl...."
4,10392,904.0,units,2690.91,units,79649.0,79650.0,579106.0,1.08,2.0,627519.26,579105.90,48413.36,968.27,-1.0,0.92,1.0,0.92,"Live pure-bred swine, weighing >= 50 kg (excl...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9178,950632,22.0,units,0.00,NR,14.0,0.0,1031.0,1.04,6.0,1074.10,0.00,1074.10,64.45,14.0,NMR,NMR,NaN,Golf balls
9179,950632,22.0,units,0.00,NR,14.0,0.0,1031.0,1.04,6.0,1074.10,0.00,1074.10,64.45,14.0,NMR,NMR,NaN,Golf balls
9180,961320,17.0,units,0.00,NR,2.0,0.0,360.0,1.04,18.0,372.96,0.00,372.96,67.13,2.0,NMR,NMR,NaN,"Pocket lighters, gas fuelled, refillable"
9181,961320,17.0,units,0.00,NR,2.0,0.0,360.0,1.04,18.0,372.96,0.00,372.96,67.13,2.0,NMR,NMR,NaN,"Pocket lighters, gas fuelled, refillable"
9182,961320,17.0,units,0.00,NR,2.0,0.0,360.0,1.04,18.0,372.96,0.00,372.96,67.13,2.0,NMR,NMR,NaN,"Pocket lighters, gas fuelled, refillable"

In [63]:
df = df[['hs_code', 'commodity', 'br_x_q', 'br_x_unit', 'py_m_q', 'py_m_unit', 'br_x_nt_wgt',
       'py_m_nt_wgt', 'br_x_value', 'itic_rate', 'applied_tariff',
       'adj_x_value', 'py_m_value', 'trade_gap', 'est_tax_loss', 'wgt_gap',
       'value_ratio', 'wgt_ratio', 'density']]

In [64]:
df

,hs_code,commodity,br_x_q,br_x_unit,py_m_q,py_m_unit,br_x_nt_wgt,py_m_nt_wgt,br_x_value,itic_rate,applied_tariff,adj_x_value,py_m_value,trade_gap,est_tax_loss,wgt_gap,value_ratio,wgt_ratio,density
0,10310,Pure-bred breeding swine,641.0,units,0.00,NR,58244.0,55587.0,649041.0,1.08,0.0,703300.83,649040.72,54260.11,0.00,2657.0,0.92,0.95,0.97
1,10310,Pure-bred breeding swine,641.0,units,0.00,NR,58244.0,55587.0,649041.0,1.08,0.0,703300.83,649040.72,54260.11,0.00,2657.0,0.92,0.95,0.97
2,10310,Pure-bred breeding swine,641.0,units,0.00,NR,58244.0,55587.0,649041.0,1.08,0.0,703300.83,649040.72,54260.11,0.00,2657.0,0.92,0.95,0.97
3,10392,"Live pure-bred swine, weighing >= 50 kg (excl....",904.0,units,2690.91,units,79649.0,79650.0,579106.0,1.08,2.0,627519.26,579105.90,48413.36,968.27,-1.0,0.92,1.0,0.92
4,10392,"Live pure-bred swine, weighing >= 50 kg (excl....",904.0,units,2690.91,units,79649.0,79650.0,579106.0,1.08,2.0,627519.26,579105.90,48413.36,968.27,-1.0,0.92,1.0,0.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9178,950632,Golf balls,22.0,units,0.00,NR,14.0,0.0,1031.0,1.04,6.0,1074.10,0.00,1074.10,64.45,14.0,NMR,NMR,NaN
9179,950632,Golf balls,22.0,units,0.00,NR,14.0,0.0,1031.0,1.04,6.0,1074.10,0.00,1074.10,64.45,14.0,NMR,NMR,NaN
9180,961320,"Pocket lighters, gas fuelled, refillable",17.0,units,0.00,NR,2.0,0.0,360.0,1.04,18.0,372.96,0.00,372.96,67.13,2.0,NMR,NMR,NaN
9181,961320,"Pocket lighters, gas fuelled, refillable",17.0,units,0.00,NR,2.0,0.0,360.0,1.04,18.0,372.96,0.00,372.96,67.13,2.0,NMR,NMR,NaN
9182,961320,"Pocket lighters, gas fuelled, refillable",17.0,units,0.00,NR,2.0,0.0,360.0,1.04,18.0,372.96,0.00,372.96,67.13,2.0,NMR,NMR,NaN